[package]
name = "examples"
version = "0.1.0"
authors = ["Chris Ohk <utilforever@gmail.com>"]
edition = "2018"

[dependencies.runeterra]
path = "../build/runeterra"

[[bin]]
name = "runeterra_console"
path = "runeterra_console.rs" 